### ISSUE TITLE
Make calc.py

### ISSUE THREAD

**Issue by darkmastermindz** [darkmastermindz/gitworkshop-hansel#2]
# Calculator Features
* Take in 2 numbers.
* Need add, subtract, multiply, divide, and exponential.
* Display result

**Comment by sgaug** [comment]
I'll do add

**Comment by anup-deshpande** [comment]
I'll do substraction

**Comment by dhodapkarsoham** [comment]
I'll do multiplication

**Comment by JMC792** [comment]
ill do division

**Comment by darkmastermindz** [comment]
Workshop over. Closed.
